# Generated by Django 6.0.3 on 2026-04-05 09:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0006_order_expires_at_order_status'),
    ]

    operations = [
        migrations.RenameField(
            model_name='tickettype',
            old_name='quantity',
            new_name='available_quantity',
        ),
        migrations.AddField(
            model_name='tickettype',
            name='total_quantity',
            field=models.IntegerField(default=0),
            preserve_default=False,
        ),
    ]
